### PR TITLE
fix: properly handle webpack loaders

### LINKED ISSUE #17: path.extname for extension checks will break with webpack loaders
The use of path.extname to extract the extension of a require (done [here](https://github.com/ariporad/pirates/blob/master/lib/index.js#L17)) is actually an inherent bug, as `path` does the extension extract based on the assumption that the entire string is a pure filename, whereas node requires don't have to conform to these. Webpack loaders take advantage of this, so you can do something like this:

```
require("file!basefile.txt?name=monkey.d.luffy");
```

Which will copy the "basefile.txt" resource as the file "monkey.d.luffy" somewhere else. In strings like these, `path` cannot extract the extension, as it assumes the strings is a true file path rather than a URI, and so it will find `.luffy` as extension.

It would probably worth to at the very least strip off URI arguments, using something like

``````
function shouldCompile(filename, exts, matcher, ignoreNodeModules) {
  if (typeof filename !== 'string') return false;
  // strip URI arguments if necessary (used by webpack etc.)
  var qpos = filename.indexOf('?');
  if (qpos > -1) filename = filename.substring(0,qpos);
  if (exts.indexOf(path.extname(filename)) === -1) return false;
  filename = path.resolve(filename);
  if (ignoreNodeModules && nodeModulesRegex.test(filename)) return false;
  if (matcher && typeof matcher === 'function') return !!matcher(filename);
  return true;
}```
``````

### PR DESCRIPTION
**Pull request by ariporad**
Fixes #17.

### CODE REVIEW

**Comment by Pomax** [comment]
A possible test for this would be to have a file with something like:

```
var emptyTransform = function(source, filename) {
  return "module.exports = {};\n";
};

addHook(emptyTransform, ['text']);

require('file!something.text?name=thing.with.dot');
```

**Comment by Pomax** [comment]
hm, it looks like this won't work, as pirates kicks in after the base file consultation goes through, so node will try to get the file content, *then* hand it over to pirates, which will fail on webpack syntax.

There are ways around this (loader instructions in a webpack.config.js for instance) so I guess it might be a case of "document that this won't work, rather than fix"?

**Comment by ariporad** [comment]
@Pomax: Ok, I'll close this, would you mine submitting a PR to document it? You seem to know a good bit more about this than me.

**Comment by Pomax** [comment]
will do

**Comment by Pomax** [comment]
filed as https://github.com/ariporad/pirates/pull/21

**Pull request closed without merging**
