### PR TITLE
docs around what syntax Pirates can't work with

### PR DESCRIPTION
**Pull request by Pomax**
Mostly because of webpack, but this will likely also affect browserify etc.

### CODE REVIEW

**Comment by ariporad** [comment]
Hmm... Reading this, it doesn't really make any sense, because pirates is Node.js only. (It wouldn't make any sense in the browser, you'd want to pre-compile your files). And AFAIK, require-hooking isn't really a thing in the browser.

Does that make sense?

**Comment by Pomax** [comment]
not given things like React, where the code "doesn't care" where it runs. You write your code as "whatever-ends-up-rendering-it" agnostic regular old Node.js code, and depending on whether or not you `require()` in a DOM renderer (or a native iOS renderer, etc) the deployment will be on a desktop, or a phone or the browser, etc. I, personally, ended up using pirates because I'm writing a React application that gets webpacked for the browser, but also needs library-compiling for using it in node.js to do static HTML file generation: code that will never see a browser.

**Comment by ariporad** [comment]
@Pomax: but there's no such thing as a require hook in the browser, because everything is required/read from disk ahead of time. You'd want a loader or a transform. Plus, it's *_really_* bad practice to compile everything at runtime in the clients browser.

**Comment by Pomax** [comment]
that's not what I meant. Webpack and friends bundle all the code offline before a browser is even involved. However, if you need to run your *own* processing, parallel to these kind of processing, you need pirates to filter out browserify/webpack/etc stuff. And that won't always succeed, certainly not when you're using the syntax this PR talks about.

**Comment by ariporad** [comment]
@Pomax: No, if you want to do your own transforms with browserify/webpack then you need something else. As of right now, pirates only deals with node require hooks.

As much as I'd like to be able to hook into webpack, I highly doubt that it's possible, as browserify transforms are compile time, but pirates runs at runtime.

**Comment by Pomax** [comment]
that's my point. If I use webpack loaders to preprocess my data for bundling, I can *also* use those *exact same loaders* to do the preprocessing of my data for use in base Node.js  (that's the whole power of webpack loaders, as sync transformers).

**Comment by ariporad** [comment]
@Pomax: Oh,  Ok, I see what you mean. Give me a few hours to think on this change, I'm not sure if documenting that webpack custom syntax doesn't work in node is within the scope of this project.

**Comment by Pomax** [comment]
Sure thing, but documentation is always in scope. If one person runs into this (in this case, me), other people are virtually guaranteed to also run into this but without being as willing to file issues about it =)

**Pull request closed without merging**
