### PR TITLE
allow importing in more ways

### PR DESCRIPTION
**Pull request by graingert**
```js
import addHook from 'pirates';
```
```js
import { addHook } from 'pirates';
```
```js
import pirates from 'pirates';
const { addHook } = pirates;
```

### CODE REVIEW

**Comment by danez** [comment]
That looks good to me, just wondering why you want this?

**Comment by graingert** [comment]
I tried to use pirates as documented:

```js
import pirates from 'pirates';
const { addHook } = pirates;
```

And it didn't work

**Comment by graingert** [comment]
And it make sense to use it as:

`import addHook from 'pirates';`

**Comment by danez** [comment]
The documentation uses `require('pirates')`.

The es variant right now would be `import { addHook } from 'pirates'`.

I think I would rather update README and describe how to import it. Too many ways of doing one thing just leads to confusion I think.

**Pull request closed without merging**
